FROM node:12.13-alpine
ENV PORT 3000
WORKDIR /app
ADD package.json /app/package.json
RUN npm config set registry http://registry.npmjs.org
RUN npm install

ADD . /app

EXPOSE $PORT

CMD ["npm", "run", "start"]